name: "Coveralls"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: npm install, make test-coverage
      run: |
        cd packages
        cd common
        npm install
        npm test -- --coverage

    - name: Report Coveralls
      run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

